sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t astridkrause/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true astridkrause/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "eu-central-1"
    app: "docker-react-training"
    env: "DockerReactTraining-env"
    bucket_name: "elasticbeanstalk-eu-central-1-441410799106"
    bucket-path: "docker-react-training"
    on:
        branch: main    
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY