language: generic
sudo: required
services: 
    - docker

 before install:
    - docker build -t astridkrause/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true astridkrause/docker-react npm run test